### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by DiegoMagdaleno** [mikedilger/solvent#9]
I kind of want to use this project, personally but I don't know if some project like adding Boolean logic or version numbers are still active projects or if I should try to take them on my own.

**Comment by mikedilger** [comment]
I have not actively worked on this in a long time, as you can tell from the commit dates. And I don't have any current ambitions to work on those enhancements like boolean logic anymore.

 But I'm both happy to fix bugs or minor issues and to take pull requests. I could even imaging handing over the project to someone if they were keen enough and making good progress.

I use this project in some of my other projects as a way to order database schema migrations that are not strictly sequential that get merged together from separate git branches.  It does that well enough for my purposes.

**Comment by DiegoMagdaleno** [comment]
I am making a package manager and I plan on using this most likely, I fork it and try to make my own changes and fixes :D, thank you.

**Comment by mikedilger** [comment]
Solvent is very simple. All it does is builds a dep graph and walks it. And it's not very smart or efficient as it rewalks for each iteration IIRC. It doesn't use any of the more advanced rust data structures, it's not asynchronous or threaded, it doesn't handle anything like semver or even boolean logic. You could rewrite the core in less than an hour and probably under 30 lines of code.

If I were you I'd start from scratch or look for a more advanced project. Peek at what I did, but also think about how you are going to handle boolean logic and semver before you commit to a set of data structures.

And good luck.

**Comment by DiegoMagdaleno** [comment]
Thanks, I look into the best option, and sure I am going to look at this algortihm
